set -o errexit

curl \
-X POST https://githubconnector.34.77.213.54.xip.io/webhook -k \
-H "content-type: application/json" \
-H "X-GitHub-Delivery: bdf3eca0-b386-11e9-987b-e98f6eaab462" \
-H "X-GitHub-Event: watch" \
-H "X-Hub-Signature: sha1=3fa91c22ee3b85a023fd18ecc01e49c279b95f42" \
-d '{
  "action": "started",
  "repository": {
    "id": 196965374,
    "node_id": "MDEwOlJlcG9zaXRvcnkxOTY5NjUzNzQ=",
    "name": "heroku-go-test",
    "full_name": "rafalpotempa/heroku-go-test",
    "private": false,
    "owner": {
      "login": "rafalpotempa",
      "id": 33723064,
      "node_id": "MDQ6VXNlcjMzNzIzMDY0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/33723064?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rafalpotempa",
      "html_url": "https://github.com/rafalpotempa",
      "followers_url": "https://api.github.com/users/rafalpotempa/followers",
      "following_url": "https://api.github.com/users/rafalpotempa/following{/other_user}",
      "gists_url": "https://api.github.com/users/rafalpotempa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rafalpotempa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rafalpotempa/subscriptions",
      "organizations_url": "https://api.github.com/users/rafalpotempa/orgs",
      "repos_url": "https://api.github.com/users/rafalpotempa/repos",
      "events_url": "https://api.github.com/users/rafalpotempa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rafalpotempa/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rafalpotempa/heroku-go-test",
    "description": "Heroku GitHub go test",
    "fork": false,
    "url": "https://api.github.com/repos/rafalpotempa/heroku-go-test",
    "forks_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/forks",
    "keys_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/teams",
    "hooks_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/hooks",
    "issue_events_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/events",
    "assignees_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/tags",
    "blobs_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/languages",
    "stargazers_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/stargazers",
    "contributors_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/contributors",
    "subscribers_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/subscribers",
    "subscription_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/subscription",
    "commits_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/merges",
    "archive_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/downloads",
    "issues_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/labels{/name}",
    "releases_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rafalpotempa/heroku-go-test/deployments",
    "created_at": "2019-07-15T09:14:15Z",
    "updated_at": "2019-07-31T11:31:30Z",
    "pushed_at": "2019-07-25T07:56:42Z",
    "git_url": "git://github.com/rafalpotempa/heroku-go-test.git",
    "ssh_url": "git@github.com:rafalpotempa/heroku-go-test.git",
    "clone_url": "https://github.com/rafalpotempa/heroku-go-test.git",
    "svn_url": "https://github.com/rafalpotempa/heroku-go-test",
    "homepage": "",
    "size": 9993,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Go",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 0,
    "open_issues": 1,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rafalpotempa",
    "id": 33723064,
    "node_id": "MDQ6VXNlcjMzNzIzMDY0",
    "avatar_url": "https://avatars0.githubusercontent.com/u/33723064?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rafalpotempa",
    "html_url": "https://github.com/rafalpotempa",
    "followers_url": "https://api.github.com/users/rafalpotempa/followers",
    "following_url": "https://api.github.com/users/rafalpotempa/following{/other_user}",
    "gists_url": "https://api.github.com/users/rafalpotempa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rafalpotempa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rafalpotempa/subscriptions",
    "organizations_url": "https://api.github.com/users/rafalpotempa/orgs",
    "repos_url": "https://api.github.com/users/rafalpotempa/repos",
    "events_url": "https://api.github.com/users/rafalpotempa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rafalpotempa/received_events",
    "type": "User",
    "site_admin": false
  }
}'
